### ISSUE TITLE
feat: add data model validation

### ISSUE THREAD

**Issue by xseman** [xseman/bysquare#17]

**Comment by LukasBicus** [comment]
- is usage of 3rd party libraries suitable (f.e. for validation of IBAN)
- should the validation be arbitrary (configurable) or built in?

**Comment by LukasBicus** [comment]
I'm going to implement this.

**Comment by xseman** [comment]
After a moment of consideration, it makes sense for the first iteration to optionally validate ISO standards that have a strict format. This would be especially useful for applications that consume the generated code and are limited to serialization for ISO standards (banks mobile applications).

To start, we can focus on checking three types of information:

- `CurrencyCode` (ISO 4217)
- `CountryCode` (ISO 3166)
- `PaymentDueDate` (ISO 8601)
- `bic` (ISO 9362)
- `iban` (ISO 13616:2003)

Maybe there are more fields with standards?  @LukasBicus, could you take a look and see if I missed any?
It seems like [validator.js](https://github.com/validatorjs/validator.js) might be a good option for this task, since it supports all the standards I've identified so far.

**Comment by LukasBicus** [comment]
`validator.js` will be a great choice. I checked the references section of `specification_v1.1.0.pdf`. I will be a little more specific - the `ISO 3166­1 alpha­3` will be used for country code validation (for example `SVK`).

I found no more ISO standards in the document.
