### ISSUE TITLE
Unable to decode data from qrcodes on page https://bsqr.co/generator/?from=product_page

### ISSUE THREAD

**Issue by peter-rybar** [xseman/bysquare#2]
`0004G0005ES17OQ09C98Q7ME34TCR3V71LVKD2AE6EGHKR82DKS5NBJ3331VUFQIV0JGMR743UJCKSAKEM9QGVVVOIVH000
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Checksum conflict".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`

**Comment by xseman** [comment]
Thanks for reporting this issue.

Before i can debug the issue, I need to verify my assumption that you've taken 
these steps, correct me if I'm wrong:

- Generate a QR code from the form at https://bsqr.co/generator
- Scanned the QR code and extracted the string
- Run the parser on the extracted string
