### ISSUE TITLE
No import named PaymentOption in v2.8.1

### ISSUE THREAD

**Issue by Glogo** [xseman/bysquare#22]
After updating to version 2.8.1 I'm getting error:

```
import { encode, PaymentOptions } from 'bysquare';
                 ^^^^^^^^^^^^^^
SyntaxError: The requested module 'bysquare' does not provide an export named 'PaymentOptions'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

I am using it in Node.js v18.14.2 module without running typescript. Could it be related to the recent tsconfig changes in bysquare?

**Comment by Glogo** [comment]
After further reviewing your dist folder the "types.js" file is empty, so probably some issue with the ts build and packaging?

<img width="718" alt="Screenshot 2024-03-18 at 15 34 56" src="https://github.com/xseman/bysquare/assets/1913799/07947d22-a8e1-41f6-9c38-c540682f023e">

**Comment by xseman** [comment]
It's related to `const enum` which omits js and act more like macro and place values where it's used in outcome js, `types.d.ts` keeps the values so you should get type-hints

**Comment by xseman** [comment]
It's related to const enum which are inlined Javascript. The `types.d.ts` file still retains these values, but it fails to import in Javascript because it doesn't import any varaibles. I'll switch back to regular enums for now, to avoid this problem. 

@Glogo 
What do you think about changing it to standard `as const` to avoid compilation problems like this one?

**Comment by xseman** [comment]
Fixed by https://github.com/xseman/bysquare/pull/23

**Comment by Glogo** [comment]
> What do you think about changing it to standard `as const` to avoid compilation problems like this one?

I don't have any preference regarding this, your change did the trick though, thanks
