### ISSUE TITLE
Chybaju dalsie polia

### ISSUE THREAD

**Issue by fafayqa** [xseman/bysquare#31]
Bolo by fajn, keby tento kod obsahoval VSETKY POLIA, ktore je mozne vyplnit, nie len tie 3 ci 4 (Sprava pre prijimatela, Nazov prijimatela, Datum vykonania/splatnosti, Specificky symbol, Konstantny symbol).
Alebo povedane inak: bolo by dobre vediet, ake su nazvy pre chybajuce polia v tomto kode:

```
payments: [
    {
        type: PaymentOptions.PaymentOrder,
        amount: this._ammount,
        bankAccounts: [{ iban: this._iban }],
        currencyCode: CurrencyCode.EUR,
        variableSymbol: this._variable
    }
]
```

Minimalne pole "Sprava pre prijimatela" je totalna nutnost, bez neho nemozem sparovat platbu s e-mailom (v sprave mi totiz klient uvadza svoj e-mail a tak to viem sparovat, dohladat a kontaktovat ho).

**Comment by xseman** [comment]
Ak správne chápem, používaš JavaScript bez typov a nedostávaš hinty. Momentálne robím s VSCode, ktorý vie v JS typy hintovať, ak ich knižnica obsahuje. Ak nemáš hinty o typoch, pozri sa na typ `SimplePayment`, kde sú definované základné dáta pre platby.

https://github.com/xseman/bysquare/blob/master/src/types.ts#L177

**Comment by xseman** [comment]
@lukasbicus Napadá ťa ako zlepšiť dokumentáciu? Nerád by som dával obrovské examples do hlavného README

**Comment by lukasbicus** [comment]
@xseman - suhlasím s tým, že README má byť stručné. Zároveň si tiež myslím, že pre @fafayqa a iných užívateľov by bolo naozaj prínosné vedieť, či tento package vie uspokojiť ich potreby ešte predtým, než si ho nainštalujú a vidia nápovedu v IDE.

Riešením by mohlo byt vygenerovať z JSdoc dokumentáciu a odkázať naňu z README.md. Prvé video, ktoré mi podhodil youtube s návodom je napr. toto: https://www.youtube.com/watch?v=FrUQnR4GTpQ

**Comment by xseman** [comment]
JSdoc vyzerá fajn, dosť mi to pripomína [TypeDoc](https://typedoc.org/). Nad generovaním dokumentácie som taktiež rozmýšlal, no typ človeka ktorý otvorí takúto dokumentáciu už skor nainštaluje package, alebo pozrie zdrojáky interface kde to uvidí podobne ako v takejto dokumentácí.

@lukasbicus čo povieš na to, že upravíme https://github.com/xseman/bysquare?tab=readme-ov-file#adavanced-usage dali by sme ho ako `<details>` element so všetkými vyplnenými fields, tým padom bude schovaný a nezaberie to toľko miesta v README.

**Comment by lukasbicus** [comment]
Nepodceňoval by som potrebu užívateľov mať plnohodnotnú dokumentáciu. Samozrejme použiť details je tiež cesta.
