### ISSUE TITLE
feat: add payment helper functions

### ISSUE THREAD

**Issue by xseman** [xseman/bysquare#38]

**Comment by abhishekpaturkar** [comment]
any description ?

**Comment by xseman** [comment]
@abhishekpaturkar I was thinking about simplifying the data build for the encode function, but now I believe using helper functions like `createPaymentOrder()` for `PaymentOrder`, `StandingOrder` and `DirectDebit` might be better. I'm still not completely sure, though.

**Comment by abhishekpaturkar** [comment]
By using these helper functions you mentioned, we can simplify `serialize` function

**Comment by xseman** [comment]
Implemented by https://github.com/xseman/bysquare/pull/48
