### ISSUE TITLE
Some QR codes do not work

### ISSUE THREAD

**Issue by Matej4386** [xseman/bysquare#5]
Hello,
first thank you very much for this work. It helps me a lot.

During testing we have found out that some QR codes do not work and we can't find why. We are testing with several mobile bank apps (broken QR codes do not work for none)

We are using version 1.0.7 with qrcode 1.5.0.

For example (working solution):
"Amount": "28",
"BankAccounts": "1",
"CurrencyCode": "EUR",
"IBAN": "SK12345600000000000123456",
"PaymentNote": "Name A",
"PaymentOptions": "1",
"Payments": "1",
"SpecificSymbol": "4129",
"VariableSymbol": "2268824129"

Not working:
"Amount": "74",
"BankAccounts": "1",
"CurrencyCode": "EUR",
"IBAN": "SK12345600000000000123456",
"PaymentNote": "Name B",
"PaymentOptions": "1",
"Payments": "1",
"SpecificSymbol": "4129",
"VariableSymbol": "2268824129"

I am open to testing just let me know. Due to privacy reason I am not sharing whole information.

**Comment by xseman** [comment]
Thanks @Matej4386 for reporting this issue.

Can you try scanning the QR using the Tatra Banka app? I have not been able to 
reproduce the problem using your model example.

**Comment by Matej4386** [comment]
Hi @xseman,
thank you for quick response. Model is not the exact one (I cant post the not working model here) - I can sent it to you.

**Comment by xseman** [comment]
So after testing we found that the non-ASCII characters are invalid, not sure if 
any banking app will automatically convert them to basic ASCII, but I wouldn't 
count on it. The solution could be for the `generate` function to remove the 
diacritics from `PaymentNote` as side-effect.

**Comment by Matej4386** [comment]
Resolved. Thank you very much

**Comment by xseman** [comment]
v1.3.2 will convert latin-1 to basic letters. f9932a5bafed18bda9c5abb53730d823f1824d9c
