### ISSUE TITLE
Fio: Nepodporovaná verzia BySquare QR kódu; Raiffeisen: CHYBA SKENOVANIA

### ISSUE THREAD

**Issue by nolimitdev** [xseman/bysquare#9]
Takže zrejme ako bolo spomenuté tu https://github.com/xseman/bysquare/issues/3 funguje to asi málo kde, možno len pre tatrabanku kde to autor testoval.

UPDATE: nefunkčné taktiež v Raiffeisen appke: CHYBA SKENOVANIA
Načítané údaje nie sú správne. Vyplňte, prosím, údaje ručne.

https://raw.githubusercontent.com/xseman/bysquare/master/docs/examples/web/index.html =>
https://paybysquare.tiiny.site/

**Comment by xseman** [comment]
Vdaka za issiue, rád pomôžem. V html example mám verziu ktorá bola deprecated, skús:

```ts
import { generate } from "https://esm.sh/bysquare@2.6.0/";
```

**Comment by nolimitdev** [comment]
Funguje :) Vďaka.
